#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::Deserialize;
use std::{
    sync::{
        atomic::{AtomicBool, Ordering},
        Arc, Mutex,
    },
    time::Duration,
};
use tauri_plugin_shell::process::{CommandChild, CommandEvent};
use tauri_plugin_shell::ShellExt;

/// Configuration generated by predev.ts
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct DawConfig {
    state_port: u16,
    mcp_port: u16,
    state_token: String,
}

impl DawConfig {
    fn load() -> Self {
        // Try to load from JSON file (written by predev.ts)
        let config_path = std::path::Path::new(".daw-config.json");
        if config_path.exists() {
            if let Ok(contents) = std::fs::read_to_string(config_path) {
                if let Ok(config) = serde_json::from_str(&contents) {
                    return config;
                }
            }
        }

        // Fallback to env vars or defaults
        DawConfig {
            state_port: std::env::var("DAW_STATE_PORT")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(43125),
            mcp_port: std::env::var("DAW_MCP_PORT")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(43124),
            state_token: std::env::var("DAW_STATE_TOKEN")
                .unwrap_or_else(|_| uuid::Uuid::new_v4().to_string()),
        }
    }
}

/// Tracks spawned sidecar child handles for graceful shutdown.
#[derive(Clone, Default)]
struct SidecarHandles(Arc<Mutex<Vec<CommandChild>>>);

impl SidecarHandles {
    fn add(&self, child: CommandChild) {
        if let Ok(mut handles) = self.0.lock() {
            handles.push(child);
        }
    }

    fn kill_all(&self) {
        if let Ok(mut handles) = self.0.lock() {
            for child in handles.drain(..) {
                let _ = child.kill();
            }
        }
    }
}

/// Wait for a health check endpoint to respond successfully.
async fn wait_for_health(base_url: &str, token: &str, timeout: Duration) -> bool {
    let client = match reqwest::Client::builder()
        .timeout(Duration::from_secs(2))
        .build()
    {
        Ok(c) => c,
        Err(_) => return false,
    };

    let url = format!("{}/api/health", base_url);
    let start = std::time::Instant::now();

    while start.elapsed() < timeout {
        let request = client
            .get(&url)
            .header("Authorization", format!("Bearer {}", token));
        if let Ok(resp) = request.send().await {
            if resp.status().is_success() {
                return true;
            }
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }

    false
}

fn main() {
    let sidecar_handles = SidecarHandles::default();
    let shutdown_flag = Arc::new(AtomicBool::new(false));

    // Clone for use after setup closure moves the originals
    let sidecar_handles_for_cleanup = sidecar_handles.clone();

    tauri::Builder::default()
        .manage(sidecar_handles.clone())
        .plugin(tauri_plugin_shell::init())
        .on_window_event({
            let sidecar_handles = sidecar_handles.clone();
            let shutdown_flag = shutdown_flag.clone();
            move |_window, event| {
                if let tauri::WindowEvent::CloseRequested { .. } = event {
                    eprintln!("[daw] Window closing, terminating sidecars...");
                    shutdown_flag.store(true, Ordering::SeqCst);
                    sidecar_handles.kill_all();
                }
            }
        })
        .setup(move |app| {
            let sidecar_handles = sidecar_handles.clone();
            let shutdown_flag = shutdown_flag.clone();

            // Load config from JSON file written by predev.ts
            let config = DawConfig::load();
            let final_mcp_port = config.mcp_port;
            let final_state_port = config.state_port;
            let state_token = config.state_token;

            eprintln!(
                "[daw] Using ports: MCP={} STATE={}",
                final_mcp_port, final_state_port
            );

            let state_base_url = format!("http://127.0.0.1:{}", final_state_port);

            // Start the state server sidecar FIRST (MCP depends on it)
            let statecar = app
                .shell()
                .sidecar("daw-server")
                .expect("failed to create daw-server sidecar command")
                .env("DAW_STATE_PORT", format!("{}", final_state_port))
                .env("DAW_STATE_TOKEN", state_token.clone());

            let (mut state_rx, state_child) = statecar
                .spawn()
                .expect("failed to spawn daw-server sidecar");

            sidecar_handles.add(state_child);

            let shutdown_flag_state = shutdown_flag.clone();
            tauri::async_runtime::spawn(async move {
                while let Some(event) = state_rx.recv().await {
                    if shutdown_flag_state.load(Ordering::SeqCst) {
                        break;
                    }
                    match event {
                        CommandEvent::Stdout(line) => {
                            let line = String::from_utf8_lossy(&line);
                            print!("[daw-server] {line}");
                        }
                        CommandEvent::Stderr(line) => {
                            let line = String::from_utf8_lossy(&line);
                            eprint!("[daw-server] {line}");
                        }
                        CommandEvent::Terminated(payload) => {
                            eprintln!("[daw-server] terminated: {:?}", payload);
                            break;
                        }
                        _ => {}
                    }
                }
            });

            // Spawn the MCP sidecar in setup (not in an async block that escapes)
            let mcp_sidecar = app
                .shell()
                .sidecar("daw-mcp")
                .expect("failed to create daw-mcp sidecar command")
                .env("DAW_MCP_PORT", format!("{}", final_mcp_port))
                .env("DAW_STATE_PORT", format!("{}", final_state_port))
                .env("DAW_STATE_TOKEN", state_token.clone());

            // Wait for state server to be healthy, then spawn MCP
            let state_base_url_clone = state_base_url.clone();
            let state_token_clone = state_token.clone();
            let sidecar_handles_mcp = sidecar_handles.clone();
            let shutdown_flag_mcp = shutdown_flag.clone();

            tauri::async_runtime::spawn(async move {
                eprintln!("[daw] Waiting for state server to be ready...");

                if !wait_for_health(
                    &state_base_url_clone,
                    &state_token_clone,
                    Duration::from_secs(30),
                )
                .await
                {
                    eprintln!(
                        "[daw] Warning: State server health check timed out, continuing anyway"
                    );
                } else {
                    eprintln!("[daw] State server is ready");
                }

                if shutdown_flag_mcp.load(Ordering::SeqCst) {
                    return;
                }

                // Now spawn the MCP sidecar
                let (mut rx, child) = match mcp_sidecar.spawn() {
                    Ok(result) => result,
                    Err(e) => {
                        eprintln!("[daw] Failed to spawn daw-mcp sidecar: {}", e);
                        return;
                    }
                };

                sidecar_handles_mcp.add(child);

                while let Some(event) = rx.recv().await {
                    if shutdown_flag_mcp.load(Ordering::SeqCst) {
                        break;
                    }
                    match event {
                        CommandEvent::Stdout(line) => {
                            let line = String::from_utf8_lossy(&line);
                            print!("[daw-mcp] {line}");
                        }
                        CommandEvent::Stderr(line) => {
                            let line = String::from_utf8_lossy(&line);
                            eprint!("[daw-mcp] {line}");
                        }
                        CommandEvent::Terminated(payload) => {
                            eprintln!("[daw-mcp] terminated: {:?}", payload);
                            break;
                        }
                        _ => {}
                    }
                }
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

    // Ensure sidecars are terminated on exit
    eprintln!("[daw] Application exiting, cleaning up...");
    sidecar_handles_for_cleanup.kill_all();
}
