#!/usr/bin/env bun

import { randomUUID } from "node:crypto";
import { createServer } from "node:net";
import { $ } from "bun";

// Clean up any orphan processes from previous dev sessions before starting.
// This prevents "port already in use" errors when restarting dev.
console.log("[predev] Cleaning up orphan processes...");
await $`bun run --cwd ../.. cleanup:orphans`.quiet().nothrow();

// Generate token and find available ports
function findAvailablePort(preferred: number): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.listen(preferred, "127.0.0.1", () => {
      server.close(() => resolve(preferred));
    });
    server.on("error", () => {
      // Port in use, try next
      const next = preferred + 1;
      if (next > preferred + 100) {
        reject(new Error(`Could not find available port near ${preferred}`));
      } else {
        findAvailablePort(next).then(resolve, reject);
      }
    });
  });
}

const statePort = await findAvailablePort(Number.parseInt(Bun.env.DAW_STATE_PORT ?? "43125", 10));
const mcpPort = await findAvailablePort(Number.parseInt(Bun.env.DAW_MCP_PORT ?? "43124", 10));
const stateToken = randomUUID();

console.log(`[predev] Using ports: MCP=${mcpPort} STATE=${statePort}`);

// Write .env.local for Vite to read
const envContent = `# Auto-generated by predev.ts - do not commit
DAW_STATE_PORT=${statePort}
DAW_STATE_TOKEN=${stateToken}
DAW_MCP_PORT=${mcpPort}
`;
await Bun.write(".env.local", envContent);

// Write JSON config for main process to read
const configJson = JSON.stringify(
  {
    statePort,
    mcpPort,
    stateToken,
  },
  null,
  2,
);
await Bun.write(".daw-config.json", configJson);

// Build the sidecar binaries
console.log("[predev] Building daw-server...");
await $`cd ../server && bun run build --single`;

console.log("[predev] Building daw-mcp...");
await $`cd ../mcp && bun run build --single`;

// Determine the binary suffix based on platform/arch
function getBinarySuffix(): string {
  const platform = process.platform;
  const arch = process.arch;

  if (platform === "darwin") {
    return arch === "arm64" ? "darwin-arm64" : "darwin-x64";
  }
  if (platform === "win32") {
    return "windows-x64";
  }
  // Linux
  return arch === "arm64" ? "linux-arm64" : "linux-x64";
}

const suffix = getBinarySuffix();
const ext = process.platform === "win32" ? ".exe" : "";

// Copy binaries to resources/sidecars
await $`mkdir -p resources/sidecars`;

const serverSource = `../server/dist/daw-server-${suffix}/bin/daw-server${ext}`;
const mcpSource = `../mcp/dist/daw-mcp-${suffix}/bin/daw-mcp${ext}`;

console.log(`[predev] Copying sidecars for ${suffix}...`);
await $`cp ${serverSource} resources/sidecars/daw-server${ext}`;
await $`cp ${mcpSource} resources/sidecars/daw-mcp${ext}`;

if (process.platform !== "win32") {
  await $`chmod +x resources/sidecars/daw-server`;
  await $`chmod +x resources/sidecars/daw-mcp`;
}

console.log("[predev] Done");
